# Generated by Django 3.1.4 on 2020-12-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20201201_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Graphic Design', 'Graphic Design'), ('Web Developer', 'Web Developer'), ('Network Engineering', 'Network Engineering'), ('Mobile Developer', 'Mobile Developer'), ('IT Security', 'IT Security')], max_length=30),
        ),
    ]
