# Generated by Django 3.1.4 on 2020-12-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20201211_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='employment_status',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Freelance', 'Freelancer'), ('None', '---------')], max_length=10),
        ),
    ]
